### ISSUE TITLE
스토리북 미니멈 세팅

### ISSUE THREAD

**Issue by hismethod** [KRDS-community/krds-react#3]

**Comment by hismethod** [comment]
어떻게 하면 컴포넌트를 유지가능할 수 있게 관리할수 있을까?
- [스토리북](https://storybook.js.org/) 7+
- [ladie](https://ladle.dev/docs/)

**Comment by hismethod** [comment]
Props 있어야 한다고 생각합니다. ladie에 있는줄 알았네요

**Comment by lukasjhan** [comment]
Okay. Let's set up the storybook 7. and see :)
